server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/testDB?serverTimezone=Asia/Seoul&autoReconnect=true&validationQuery=select 1
    username: root
    password: 1234